version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opigir-spliit_server_1
      APP_PORT: 3000

  db:
    image: postgres:16.3-alpine
    environment:
      TZ: UTC
      POSTGRES_DB: spliit
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: spliit
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spliit -d spliit"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: crazymax/spliit:latest
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: UTC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: spliit
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: spliit