version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opigir-spliit_web_1
      APP_PORT: 3000

  web:
    image: crazymax/spliit:latest
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: UTC
      # Standard Prisma/Next.js URL — makes sure Prisma sees the right creds
      DATABASE_URL: postgres://spliit:UmbrelSpliit2025!@db:5432/spliit
      # (Retained for backwards compatibility with the crazymax image)
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: spliit
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: UmbrelSpliit2025!

  db:
    image: postgres:15-alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      TZ: UTC
      POSTGRES_DB: spliit
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: UmbrelSpliit2025!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spliit -d spliit"]
      interval: 5s
      timeout: 5s
      retries: 5