# docker-compose.yml
version: "3.7"

services:
  app_proxy:
    # Umbrel’s built-in reverse proxy will pick this up
    environment:
      APP_HOST: opigir-spliit_web_1
      APP_PORT: 3000

  web:
    image: crazymax/spliit:latest
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: UTC
      # Prisma/Next.js will pick this up and use it for all DB connections
      DATABASE_URL: postgres://spliit:UmbrelSpliit2025!@db:5432/spliit

  db:
    image: postgres:15-alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      TZ: UTC
      POSTGRES_DB: spliit
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: UmbrelSpliit2025!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spliit -d spliit"]
      interval: 5s
      timeout: 5s
      retries: 5