version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: opigir-spliit_web_1
      APP_PORT: 3000

  web:
    image: crazymax/spliit:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: UTC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: spliit
      POSTGRES_DB: spliit
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      POSTGRES_TIMEOUT: 60
      DATABASE_URL: postgresql://spliit:${APP_PASSWORD}@db:5432/spliit
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spliit
      POSTGRES_DB: spliit
      POSTGRES_PASSWORD: ${APP_PASSWORD}