version: "3.7"

services:
  app_proxy:
    environment:
      # opigir-spliit_web_1
      APP_HOST: opigir-spliit_web_1
      APP_PORT: 3000

  web:
    image: crazymax/spliit:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/uploads:/uploads
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: spliit
      POSTGRES_DB: spliit
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      DATABASE_URL: postgresql://spliit:${APP_PASSWORD}@db:5432/spliit
      # Enable local file uploads (no S3 needed)
      NEXT_PUBLIC_ENABLE_EXPENSE_DOCUMENTS: "true"
      # Optional: Specify local upload path
      UPLOAD_PATH: "/uploads"
      # Optional: Enable AI features with OpenAI (uncomment and add your API key)
      # NEXT_PUBLIC_ENABLE_RECEIPT_EXTRACT: "true"
      # NEXT_PUBLIC_ENABLE_CATEGORY_EXTRACT: "true"
      # OPENAI_API_KEY: your_openai_api_key_here
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spliit
      POSTGRES_DB: spliit
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata